import io
import json
import os
import re
import shutil
import tempfile
import uuid
import zipfile
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional, Dict, List, Any

import tomllib
from fastapi import FastAPI, File, HTTPException, UploadFile, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, HTMLResponse
from pydantic import BaseModel

from analyzer import ArchiveAnalyzer
from betterdependency_bridge import run_betterdependency_cli, extract_dependency_overrides, get_unresolved_dependencies
from loader_api import LoaderApiDiff
from mappings import MappingSet, MappingDiff
from planner import MigrationPlanner
from porting_engine import PortingEngine
from report import ReportBuilder
from runtime.java_manager import JavaManager, JavaResolutionError
from transformer import Transformer, rewrite_metadata, get_loader_version
from validator import Validator
from inspector_lib import ModInspector

# --- Core Configuration & Persistent Storage ---
BASE_DIR = Path(__file__).resolve().parent

# Mounts to a Persistent Disk in production to survive container reboots.
STORAGE_DIR = Path(os.getenv("STORAGE_DIR", Path(tempfile.gettempdir()) / "minecraft-porter-uploads"))
STORAGE_DIR.mkdir(parents=True, exist_ok=True)
UPLOAD_DIR = STORAGE_DIR

# 150MB limit to handle massive payload packets (e.g., Create mod) without 413 errors.
MAX_UPLOAD_SIZE = 150 * 1024 * 1024 

SUPPORTED_VERSIONS = [
    "26.2", "26.1.2", "26.1.1", "26.1", "1.21.11", "1.21.10", "1.21.9",
    "1.21.8", "1.21.7", "1.21.6", "1.21.5", "1.21.1", "1.20.6", "1.20.4",
    "1.20.1", "1.19.4", "1.19.2", "1.18.2", "1.17.1", "1.16.5", "1.16.4",
    "1.15.2", "1.14.4", "1.13.2", "1.12.2", "1.12.1", "1.12"
]

COMPATIBILITY_PROFILES = {
    "26.2": {
        "loader_notes": {
            "NeoForge": "Target NeoForge 26.2+ and verify all APIs against the latest registry and rendering changes.",
            "Fabric": "Use the latest Fabric API and loader that supports the 26.2 toolchain.",
            "Forge": "Forge support is best-effort; expect a manual review for registry and rendering changes.",
        },
        "dependencies": ["NeoForge/Forge API updates", "Fabric API update", "Latest mappings and rendering libraries"],
        "limitations": ["Some older mixin-based mods may need author-side adjustments."]
    },
    # Default fallback
    "default": {
         "loader_notes": {"Default": "Targeted compatibility update generated by the porter."},
         "dependencies": ["Refresh loader-specific dependencies"],
         "limitations": ["Manual validation recommended."]
    }
}

app = FastAPI(title="Minecraft Compatibility Updater")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# --- Pydantic Models (Incoming Packet Validation) ---
class InspectRequest(BaseModel):
    file_id: str
    loader: Optional[str] = None
    minecraft_version: Optional[str] = None

class AnalyzeDependenciesRequest(BaseModel):
    file_id: str
    loader: Optional[str] = None
    target_version: Optional[str] = None

class UpdateRequest(BaseModel):
    file_id: str
    loader: Optional[str] = None
    target_version: Optional[str] = None
    custom_neoforge_version: Optional[str] = None
    custom_javafml_version: Optional[str] = None
    custom_minecraft_version: Optional[str] = None
    dependency_overrides: Optional[dict[str, str]] = None

class BatchUpdateRequest(BaseModel):
    file_ids: list[str]
    target_version: Optional[str] = None
    custom_neoforge_version: Optional[str] = None
    custom_javafml_version: Optional[str] = None
    custom_minecraft_version: Optional[str] = None
    dependency_overrides: Optional[dict[str, str]] = None


# --- Application State (Memory Coherence) ---
# Requires `--workers 1` in production to ensure all threads share these stores.
class StoredFile:
    def __init__(self, file_id: str, path: Path, original_name: str, size: int):
        self.file_id = file_id
        self.path = path
        self.original_name = original_name
        self.size = size
        self.created_at = datetime.utcnow()

class DownloadableFile:
    def __init__(self, token: str, path: Path, filename: str, media_type: str):
        self.token = token
        self.path = path
        self.filename = filename
        self.media_type = media_type
        self.created_at = datetime.utcnow()

STORED_FILES: Dict[str, StoredFile] = {}
DOWNLOAD_FILES: Dict[str, DownloadableFile] = {}
TASKS_STORE: Dict[str, dict] = {} # The Async Job Tracker


# --- Core Utilities & Memory Sweepers ---
def sanitize_filename(filename: str) -> str:
    """Strictly prevents directory traversal exploits from malicious client payloads."""
    return Path(filename).name

def version_tuple(version: str):
    parts = []
    for part in version.split('.'):
        digits = re.match(r"(\d+)", part)
        parts.append(int(digits.group(1)) if digits else 0)
    return tuple(parts)

def cleanup_old_files():
    """Non-blocking background garbage collector to prevent memory leaks."""
    cutoff = datetime.utcnow() - timedelta(minutes=10)
    
    for fid in [k for k, v in STORED_FILES.items() if v.created_at < cutoff]:
        try: STORED_FILES[fid].path.unlink(missing_ok=True)
        except OSError: pass
        STORED_FILES.pop(fid, None)

    for tok in [k for k, v in DOWNLOAD_FILES.items() if v.created_at < cutoff]:
        try: DOWNLOAD_FILES[tok].path.unlink(missing_ok=True)
        except OSError: pass
        DOWNLOAD_FILES.pop(tok, None)
        
    for tid in [k for k, v in TASKS_STORE.items() if v.get("created_at", datetime.utcnow()) < cutoff]:
        TASKS_STORE.pop(tid, None)


# --- Parsers & Extractors ---
def load_mapping_set(version: str) -> Optional[MappingSet]:
    mapping_path = BASE_DIR / "mappings" / f"{version}-intermediary.tiny"
    return MappingSet.from_tiny(mapping_path) if mapping_path.exists() else None

def load_target_jar(version: str) -> Optional[Path]:
    jar_path = BASE_DIR / "jars" / f"minecraft-{version}.jar"
    return jar_path if jar_path.exists() else None

def detect_loader_and_metadata_in_zip(archive: zipfile.ZipFile):
    names = [n.lower() for n in archive.namelist()]
    if "fabric.mod.json" in names: return "Fabric", archive.namelist()[names.index("fabric.mod.json")]
    if "meta-inf/mods.toml" in names: return "Forge", archive.namelist()[names.index("meta-inf/mods.toml")]
    if "meta-inf/neoforge.mods.toml" in names: return "NeoForge", archive.namelist()[names.index("meta-inf/neoforge.mods.toml")]
    if "pack.mcmeta" in names: return "Vanilla", archive.namelist()[names.index("pack.mcmeta")]
    return "Unknown", None

def detect_loader_and_metadata(path: Path):
    with zipfile.ZipFile(path, "r") as archive:
        return detect_loader_and_metadata_in_zip(archive)

def _clean_version_string(raw: str) -> Optional[str]:
    if not raw or not raw.strip(): return None
    cleaned = raw.strip()
    cleaned = re.sub(r'[\[\](){}]', '', cleaned)
    if ',' in cleaned: cleaned = [p.strip() for p in cleaned.split(',') if p.strip()][0]
    cleaned = re.sub(r'^[><=~^]+\s*', '', cleaned).strip()
    return cleaned if cleaned and cleaned[0].isdigit() else None

def extract_current_version(loader: str, metadata_path: str, text: str) -> Optional[str]:
    if loader == "Fabric" or loader == "Vanilla":
        try: data = json.loads(text)
        except json.JSONDecodeError: data = {}
        if loader == "Fabric":
            depends = data.get("depends", {})
            if isinstance(depends, dict) and depends.get("minecraft"):
                return _clean_version_string(depends["minecraft"])
            if data.get("minecraft_version"):
                return _clean_version_string(data["minecraft_version"])
        if loader == "Vanilla":
            pack = data.get("pack", {})
            for k in ["supported_minecraft_version", "minecraft_version"]:
                if isinstance(pack, dict) and pack.get(k): return _clean_version_string(pack[k])
                if data.get(k): return _clean_version_string(data[k])
    
    if loader in {"Forge", "NeoForge"}:
        try: parsed = tomllib.loads(text)
        except tomllib.TOMLDecodeError: parsed = {}
        if isinstance(parsed, dict):
            for k in ["minecraft", "minecraft_version"]:
                if parsed.get(k): return _clean_version_string(parsed[k])
            deps = parsed.get("dependencies")
            if isinstance(deps, dict):
                for entries in deps.values():
                    for entry in (entries if isinstance(entries, list) else [entries]):
                        if isinstance(entry, dict) and entry.get("modId", "").lower() == "minecraft":
                            if entry.get("versionRange"): return _clean_version_string(entry["versionRange"])
            
        for pattern in [r'versionRange\s*=\s*"([^"]+)"', r'minecraft\s*=\s*"([^"]+)"', r'minecraft_version\s*=\s*"([^"]+)"']:
            match = re.search(pattern, text)
            if match: return _clean_version_string(match.group(1))
    return None

def extract_mod_metadata(loader: str, text: str) -> dict:
    result = {"mod_id": None, "mod_name": None, "mod_version": None, "description": None, "authors": [], "license": None, "homepage": None}
    if loader in {"Fabric", "Vanilla"}:
        try: data = json.loads(text)
        except: return result
        if loader == "Fabric":
            result.update({"mod_id": data.get("id"), "mod_name": data.get("name"), "mod_version": data.get("version"), "description": data.get("description"), "license": data.get("license")})
            authors = data.get("authors", [])
            result["authors"] = [a if isinstance(a, str) else a.get("name") for a in (authors if isinstance(authors, list) else [])]
            if isinstance(data.get("contact"), dict): result["homepage"] = data.get("contact").get("homepage")
    elif loader in {"Forge", "NeoForge"}:
        try: parsed = tomllib.loads(text)
        except: return result
        mods = parsed.get("mods", [])
        if isinstance(mods, list) and mods:
            m = mods[0] if isinstance(mods[0], dict) else {}
            result.update({"mod_id": m.get("modId"), "mod_name": m.get("displayName"), "mod_version": m.get("version"), "description": m.get("description", "").strip()})
            auths = m.get("authors", "")
            result["authors"] = [a.strip() for a in auths.split(",")] if isinstance(auths, str) else auths
        result.update({"license": parsed.get("license"), "homepage": parsed.get("displayURL") or parsed.get("issueTrackerURL")})
    return result

def compute_compatibility_status(current_version: Optional[str], target_version: str) -> str:
    if not current_version: return "Unknown Version"
    if current_version == target_version: return "Compatible"
    if current_version in SUPPORTED_VERSIONS: return "Needs Update"
    return "Unsupported Version"

def build_file_summary(archive_path: Path) -> dict:
    summary = {"total_files": 0, "java_files": 0, "class_files": 0, "json_files": 0, "toml_files": 0, "resource_files": 0, "texture_files": 0, "other_files": 0}
    try:
        with zipfile.ZipFile(archive_path, "r") as archive:
            for info in archive.infolist():
                if info.is_dir(): continue
                summary["total_files"] += 1
                ext = Path(info.filename.lower()).suffix
                if ext == ".java": summary["java_files"] += 1
                elif ext == ".class": summary["class_files"] += 1
                elif ext == ".json": summary["json_files"] += 1
                elif ext == ".toml": summary["toml_files"] += 1
                elif ext in {".png", ".jpg", ".jpeg", ".gif", ".tga", ".bmp"}: summary["texture_files"] += 1
                elif ext in {".mcmeta", ".properties", ".lang", ".txt", ".xml", ".cfg", ".yml", ".yaml", ".nbt"}: summary["resource_files"] += 1
                else: summary["other_files"] += 1
    except Exception: pass
    return summary

def declared_dependency_ids(loader: str, text: str) -> list[str]:
    rt = {"minecraft", "forge", "neoforge", "javafml", "fabricloader"}
    if loader == "Fabric":
        try: return sorted(k for k in json.loads(text).get("depends", {}) if k not in rt)
        except: return []
    if loader in {"Forge", "NeoForge"}:
        try:
            deps = tomllib.loads(text).get("dependencies", {})
            found = {entry.get("modId") or tid for tid, entries in (deps.items() if isinstance(deps, dict) else []) for entry in (entries if isinstance(entries, list) else [entries]) if isinstance(entry, dict)}
            return sorted(f for f in found if isinstance(f, str) and f not in rt)
        except: return []
    return []

def resolve_target_version(current_version: Optional[str], requested: Optional[str]):
    if requested and requested != "auto": return requested
    if not current_version: return SUPPORTED_VERSIONS[0]
    for version in SUPPORTED_VERSIONS:
        if version_tuple(version) <= version_tuple(current_version): return version
    return SUPPORTED_VERSIONS[-1]


# --- Asynchronous Worker Threads (The "BukkitRunnables") ---
def run_update_job(job_id: str, payload: UpdateRequest, stored: StoredFile):
    """Executes intensive AST mapping off the main event loop to prevent proxy timeouts."""
    try:
        target_mc = payload.target_version or "Unknown"
        inspector = ModInspector(stored.path, target_mc)
        inspection_results = inspector.inspect()
        
        stage = inspection_results["complexity_stage"]
        discovered_deps = inspection_results["discovered_dependencies"]
        loader = payload.loader if payload.loader and payload.loader != "auto" else inspection_results["loader"]

        target_version = resolve_target_version(inspection_results["current_version"], payload.target_version)
        dynamic_overrides = payload.dependency_overrides or {}
        
        # Run BetterDependency CLI to resolve third-party dependencies via Modrinth
        dep_analysis = run_betterdependency_cli(str(stored.path), target_version, loader)

        # Merge resolved dependency versions into the overrides.
        # User-provided overrides take priority over auto-resolved ones.
        resolved_overrides = extract_dependency_overrides(dep_analysis)
        merged_overrides = {**resolved_overrides, **dynamic_overrides}

        analyzer = ArchiveAnalyzer()
        analysis = analyzer.analyze_archive(stored.path, target_version=target_version)

        updated_archive_path = stored.path.with_name(f"{Path(stored.original_name).stem}-updated-{target_version}{stored.path.suffix}")

        engine = PortingEngine(target_version, loader)
        port_report = engine.apply_port(
            stored.path, updated_archive_path,
            custom_neoforge_version=payload.custom_neoforge_version,
            custom_javafml_version=payload.custom_javafml_version,
            custom_minecraft_version=payload.custom_minecraft_version,
            dependency_overrides=merged_overrides
        )

        token = uuid.uuid4().hex
        DOWNLOAD_FILES[token] = DownloadableFile(
            token=token, path=updated_archive_path, filename=updated_archive_path.name,
            media_type="application/java-archive" if stored.path.suffix.lower() == ".jar" else "application/zip"
        )

        # Collect unresolved dependency warnings for the report
        unresolved_deps = get_unresolved_dependencies(dep_analysis)

        # Mark ticket as resolved
        TASKS_STORE[job_id] = {
            "status": "completed",
            "filename": updated_archive_path.name,
            "size_bytes": updated_archive_path.stat().st_size,
            "download_url": f"/download/{token}",
            "changed_files": port_report.get("changed_files", []),
            "unresolved_issues": port_report.get("unresolved_issues", []),
            "bundled_dependencies_updated": port_report.get("bundled_dependencies_updated", []),
            "dependency_analysis": dep_analysis,
            "resolved_overrides": resolved_overrides,
            "unresolved_dependencies": unresolved_deps,
        }
    except Exception as exc:
        TASKS_STORE[job_id] = {"status": "failed", "error": str(exc)}


def run_batch_job(job_id: str, payload: BatchUpdateRequest, stored_files: list):
    """Executes batched multi-jar transformations securely off the main thread."""
    try:
        members = []
        for stored in stored_files:
            loader, meta_path = detect_loader_and_metadata(stored.path)
            with zipfile.ZipFile(stored.path, "r") as archive:
                text = archive.read(meta_path).decode("utf-8", errors="replace") if meta_path else ""
            c_ver = extract_current_version(loader, meta_path, text) if meta_path else None
            t_ver = resolve_target_version(c_ver, payload.target_version)
            
            out_path = stored.path.with_name(f"{stored.file_id}-{Path(stored.original_name).stem}-updated-{t_ver}{stored.path.suffix}")
            report = PortingEngine(t_ver, loader).apply_port(
                stored.path, out_path,
                custom_neoforge_version=payload.custom_neoforge_version,
                custom_javafml_version=payload.custom_javafml_version,
                custom_minecraft_version=payload.custom_minecraft_version,
                dependency_overrides=payload.dependency_overrides,
            )
            members.append({
                "file_id": stored.file_id, "output_path": out_path,
                "mod_id": extract_mod_metadata(loader, text)["mod_id"],
                "dependencies": declared_dependency_ids(loader, text),
                "changed_files": report["changed_files"],
                "unresolved_issues": report["unresolved_issues"],
                "bundled_dependencies_updated": report.get("bundled_dependencies_updated", [])
            })

        available_mods = {m["mod_id"] for m in members if m["mod_id"]}
        for m in members: m["missing_dependencies"] = [d for d in m["dependencies"] if d not in available_mods]

        bundle_path = STORAGE_DIR / f"minecraftporter-batch-{uuid.uuid4().hex}.zip"
        manifest = {"type": "minecraftporter-dependency-batch", "members": [{k: v for k, v in m.items() if k != "output_path"} for m in members]}
        
        with zipfile.ZipFile(bundle_path, "w", zipfile.ZIP_DEFLATED) as bundle:
            for m in members:
                bundle.write(m["output_path"], arcname=m["output_path"].name.split("-", 1)[-1])
            bundle.writestr("dependency-report.json", json.dumps(manifest, indent=2))

        token = uuid.uuid4().hex
        DOWNLOAD_FILES[token] = DownloadableFile(token, bundle_path, "minecraftporter-ported-mods.zip", "application/zip")
        
        TASKS_STORE[job_id] = {
            "status": "completed",
            "filename": "minecraftporter-ported-mods.zip",
            "size_bytes": bundle_path.stat().st_size,
            "download_url": f"/download/{token}",
            "changed_files": sorted({path for m in members for path in m["changed_files"]}),
            "unresolved_issues": sorted({issue for m in members for issue in m["unresolved_issues"]}),
            "missing_dependencies": sorted({dep for m in members for dep in m["missing_dependencies"]}),
            "bundled_dependencies_updated": sorted({note for m in members for note in m["bundled_dependencies_updated"]})
        }
    except Exception as exc:
        TASKS_STORE[job_id] = {"status": "failed", "error": str(exc)}


# --- Network Event Listeners (The Main Thread / ASGI Loop) ---

@app.get("/", response_class=HTMLResponse)
async def index():
    return (BASE_DIR / "index.html").read_text(encoding="utf-8")

@app.get("/styles.css")
async def styles():
    return FileResponse(BASE_DIR / "styles.css", media_type="text/css")

@app.get("/app.js")
async def app_js():
    return FileResponse(BASE_DIR / "app.js", media_type="application/javascript")

@app.post("/upload")
def upload_file(background_tasks: BackgroundTasks, file: UploadFile = File(...)):
    """Receives binary packet chunks safely, executing blocking I/O on the thread pool."""
    background_tasks.add_task(cleanup_old_files)

    if file.size and file.size > MAX_UPLOAD_SIZE:
        raise HTTPException(status_code=413, detail="Payload exceeds maximum allowed bounds.")

    safe_filename = sanitize_filename(file.filename or "file.bin")
    ext = Path(safe_filename).suffix.lower()
    if ext not in {".jar", ".zip"}:
        raise HTTPException(status_code=400, detail="Exploit blocked: Invalid file extension.")

    file_id = uuid.uuid4().hex
    destination = STORAGE_DIR / f"{file_id}{ext}"
    
    # C-level buffered I/O streaming to minimize JVM/Python heap pressure.
    try:
        with destination.open("wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
    except Exception:
        raise HTTPException(status_code=500, detail="Fatal I/O fault while flushing to disk.")
    finally:
        file.file.close()

    stored = StoredFile(file_id=file_id, path=destination, original_name=safe_filename, size=destination.stat().st_size)
    STORED_FILES[file_id] = stored
    return {"file_id": stored.file_id, "filename": stored.original_name, "size_bytes": stored.size, "message": "Uploaded safely."}

@app.post("/analyze-dependencies")
def analyze_dependencies(payload: AnalyzeDependenciesRequest):
    stored = STORED_FILES.get(payload.file_id)
    if not stored: raise HTTPException(status_code=404, detail="File pointer invalid.")

    loader, metadata_path = detect_loader_and_metadata(stored.path)
    if payload.loader and payload.loader != "auto": loader = payload.loader

    with zipfile.ZipFile(stored.path, "r") as archive:
        current_text = archive.read(metadata_path).decode("utf-8", errors="replace") if metadata_path else ""
    current_version = extract_current_version(loader, metadata_path, current_text) if metadata_path else None
    target_version = resolve_target_version(current_version, payload.target_version)

    result = run_betterdependency_cli(str(stored.path), target_version, loader)
    if result.get("status") == "error":
        raise HTTPException(status_code=500, detail=result.get("message", "Analysis pipeline crashed"))
    return result

@app.post("/inspect")
def inspect_file(payload: InspectRequest):
    stored = STORED_FILES.get(payload.file_id)
    if not stored: raise HTTPException(status_code=404, detail="File pointer invalid.")

    target_mc = payload.minecraft_version or "Unknown"
    inspector = ModInspector(stored.path, target_mc)
    inspection_results = inspector.inspect()

    loader = inspection_results["loader"]
    metadata_path = inspection_results["metadata_path"]
    if not metadata_path: raise HTTPException(status_code=400, detail="Invalid mod structure detected.")

    with zipfile.ZipFile(stored.path, "r") as archive:
        mod_meta = extract_mod_metadata(loader, archive.read(metadata_path).decode("utf-8", errors="replace"))

    target_version = resolve_target_version(inspection_results["current_version"], payload.minecraft_version)
    
    return {
        "loader": loader,
        "current_version": inspection_results["current_version"],
        "target_version": target_version,
        "compatibility_status": compute_compatibility_status(inspection_results["current_version"], target_version),
        "complexity_stage": inspection_results["complexity_stage"],
        "update_reasons": inspection_results["update_reasons"],
        "discovered_dependencies": inspection_results["discovered_dependencies"],
        "has_source_code": inspection_results["has_source_code"],
        **mod_meta,
        "file_summary": build_file_summary(stored.path),
        "metadata_path": metadata_path
    }

# --- The Task Dispatchers (Non-Blocking) ---

@app.post("/update")
def update_file(payload: UpdateRequest, background_tasks: BackgroundTasks):
    """Instantly returns a job ticket, delegating AST rewrites to a worker thread."""
    stored = STORED_FILES.get(payload.file_id)
    if not stored: raise HTTPException(status_code=404, detail="File pointer invalid.")

    job_id = uuid.uuid4().hex
    TASKS_STORE[job_id] = {"status": "processing", "created_at": datetime.utcnow()}
    
    background_tasks.add_task(run_update_job, job_id, payload, stored)
    return {"job_id": job_id, "message": "Task delegated to worker pool."}

@app.post("/update-batch")
def update_batch(payload: BatchUpdateRequest, background_tasks: BackgroundTasks):
    unique_ids = list(dict.fromkeys(payload.file_ids))
    if len(unique_ids) < 2: raise HTTPException(status_code=400, detail="Batch execution requires 2+ valid archives.")
    
    stored_files = []
    for fid in unique_ids:
        stored = STORED_FILES.get(fid)
        if not stored: raise HTTPException(status_code=404, detail=f"File pointer {fid} invalid.")
        stored_files.append(stored)

    job_id = uuid.uuid4().hex
    TASKS_STORE[job_id] = {"status": "processing", "created_at": datetime.utcnow()}
    
    background_tasks.add_task(run_batch_job, job_id, payload, stored_files)
    return {"job_id": job_id, "message": "Batch task delegated to worker pool."}

@app.get("/status/{job_id}")
def get_job_status(job_id: str):
    """Client polling endpoint to verify BukkitRunnable completion status."""
    job = TASKS_STORE.get(job_id)
    if not job: raise HTTPException(status_code=404, detail="Job ticket invalid or expired.")
    return job

@app.get("/download/{token}")
def download_file(token: str):
    """Strictly validates download tokens before serving binaries."""
    if not re.match(r"^[a-f0-9]{32}$", token): raise HTTPException(status_code=400, detail="Invalid token format.")
    downloadable = DOWNLOAD_FILES.get(token)
    if not downloadable or not downloadable.path.exists():
        raise HTTPException(status_code=404, detail="Artifact not found or expired from cache.")
    return FileResponse(path=str(downloadable.path), filename=downloadable.filename, media_type=downloadable.media_type)

@app.get("/health")
async def health():
    return {"status": "ok", "active_files": len(STORED_FILES), "jobs_running": len(TASKS_STORE)}